name: 'Mirror to BitBucket GitHub Action'
description: 'Mirrors a GitHub Git repository to BitBucket'
branding:
  icon: upload-cloud
  color: blue
inputs:
  username:
    required: true
    default: ${{ github.actor }}
  password:
    required: true
  company:
    required: true
  repository:
    required: true
    default: ${{ github.event.repository.name }}
  ignorelist:
    required: true

runs:
  using: 'docker'
  image: 'docker://101digital/mirror-to-bitbucket-github-action:latest'
  args:
    - ${{ inputs.username }}
    - ${{ inputs.password }}
    - ${{ inputs.company }}
    - ${{ inputs.repository }}
    - ${{ inputs.ignorelist }}
